## Dataset preprocessing

In [108]:
import pandas as pd
import os

In [109]:
df = pd.read_csv("./fraud_detection_transactions_dataset.csv")
df.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,...,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,TXN_33553,USER_1834,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,...,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,TXN_9427,USER_7875,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,...,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,TXN_199,USER_2734,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,...,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,TXN_12447,USER_2617,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,...,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,TXN_39489,USER_2014,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,...,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [110]:
df.columns

Index(['Transaction_ID', 'User_ID', 'Transaction_Amount', 'Transaction_Type',
       'Timestamp', 'Account_Balance', 'Device_Type', 'Location',
       'Merchant_Category', 'IP_Address_Flag', 'Previous_Fraudulent_Activity',
       'Daily_Transaction_Count', 'Avg_Transaction_Amount_7d',
       'Failed_Transaction_Count_7d', 'Card_Type', 'Card_Age',
       'Transaction_Distance', 'Authentication_Method', 'Risk_Score',
       'Is_Weekend', 'Fraud_Label'],
      dtype='object')

In [111]:
df = df.drop(columns=["User_ID", "Transaction_ID", "Timestamp"])

In [112]:
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,39.79,POS,93213.17,Laptop,Sydney,Travel,0,0,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,1.19,Bank Transfer,75725.25,Mobile,New York,Clothing,0,0,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,28.96,Online,1588.96,Tablet,Mumbai,Restaurants,0,0,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,254.32,ATM Withdrawal,76807.20,Tablet,New York,Clothing,0,0,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,31.28,POS,92354.66,Mobile,Mumbai,Electronics,0,1,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [113]:
df = pd.get_dummies(df, columns=[
    "Transaction_Type",
    "Device_Type",
    "Location",
    "Merchant_Category",
    "Card_Type",
    "Authentication_Method"
])

In [114]:
df.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,39.79,93213.17,0,0,7,437.63,3,65,883.17,0.8494,...,False,True,True,False,False,False,True,False,False,False
1,1.19,75725.25,0,0,13,478.76,4,186,2203.36,0.0959,...,False,False,False,False,True,False,False,False,False,True
2,28.96,1588.96,0,0,14,50.01,4,226,1909.29,0.8400,...,True,False,False,False,False,True,True,False,False,False
3,254.32,76807.20,0,0,8,182.48,4,76,1311.86,0.7935,...,False,False,False,False,False,True,False,True,False,False
4,31.28,92354.66,0,1,14,328.69,4,140,966.98,0.3819,...,False,False,False,False,True,False,False,False,False,True

In [115]:
df["Fraud_Label"].value_counts()

Fraud_Label
0    33933
1    16067
Name: count, dtype: int64

In [116]:
df.columns

Index(['Transaction_Amount', 'Account_Balance', 'IP_Address_Flag',
       'Previous_Fraudulent_Activity', 'Daily_Transaction_Count',
       'Avg_Transaction_Amount_7d', 'Failed_Transaction_Count_7d', 'Card_Age',
       'Transaction_Distance', 'Risk_Score', 'Is_Weekend', 'Fraud_Label',
       'Transaction_Type_ATM Withdrawal', 'Transaction_Type_Bank Transfer',
       'Transaction_Type_Online', 'Transaction_Type_POS', 'Device_Type_Laptop',
       'Device_Type_Mobile', 'Device_Type_Tablet', 'Location_London',
       'Location_Mumbai', 'Location_New York', 'Location_Sydney',
       'Location_Tokyo', 'Merchant_Category_Clothing',
       'Merchant_Category_Electronics', 'Merchant_Category_Groceries',
       'Merchant_Category_Restaurants', 'Merchant_Category_Travel',
       'Card_Type_Amex', 'Card_Type_Discover', 'Card_Type_Mastercard',
       'Card_Type_Visa', 'Authentication_Method_Biometric',
       'Authentication_Method_OTP', 'Authentication_Method_PIN',
       'Authentication_Method_Password'],
      dtype='object')

In [117]:
df.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,39.79,93213.17,0,0,7,437.63,3,65,883.17,0.8494,...,False,True,True,False,False,False,True,False,False,False
1,1.19,75725.25,0,0,13,478.76,4,186,2203.36,0.0959,...,False,False,False,False,True,False,False,False,False,True
2,28.96,1588.96,0,0,14,50.01,4,226,1909.29,0.8400,...,True,False,False,False,False,True,True,False,False,False
3,254.32,76807.20,0,0,8,182.48,4,76,1311.86,0.7935,...,False,False,False,False,False,True,False,True,False,False
4,31.28,92354.66,0,1,14,328.69,4,140,966.98,0.3819,...,False,False,False,False,True,False,False,False,False,True

In [118]:
os.makedirs('../data/', exist_ok=True)
#Saving selected dataframe
df.to_csv('../data/fraud_detection_dataset_preprocessed.csv', index=False)