## Testing different classification models

In [208]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [209]:
df = pd.read_csv("../data/fraud_detection_dataset_preprocessed.csv")
df.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
0,39.79,93213.17,0,0,7,437.63,3,65,883.17,0.8494,...,False,True,True,False,False,False,True,False,False,False
1,1.19,75725.25,0,0,13,478.76,4,186,2203.36,0.0959,...,False,False,False,False,True,False,False,False,False,True
2,28.96,1588.96,0,0,14,50.01,4,226,1909.29,0.8400,...,True,False,False,False,False,True,True,False,False,False
3,254.32,76807.20,0,0,8,182.48,4,76,1311.86,0.7935,...,False,False,False,False,False,True,False,True,False,False
4,31.28,92354.66,0,1,14,328.69,4,140,966.98,0.3819,...,False,False,False,False,True,False,False,False,False,True

In [210]:
X = df.drop(columns="Fraud_Label")
y = df["Fraud_Label"]

In [211]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [212]:
from imblearn.over_sampling import SMOTE
sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [213]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X_train_res = pd.DataFrame(
    ss.fit_transform(X_train_res),
    columns=X.columns
)

X_test = pd.DataFrame(
    ss.transform(X_test),
    columns=X.columns
)

In [214]:
X_train.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,...,Merchant_Category_Restaurants,Merchant_Category_Travel,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Authentication_Method_Biometric,Authentication_Method_OTP,Authentication_Method_PIN,Authentication_Method_Password
8950,81.31,98766.04,0,0,3,220.71,2,93,1049.70,0.7252,...,True,False,False,True,False,False,False,False,True,False
38421,95.55,61406.93,0,0,3,222.57,2,65,3279.00,0.2489,...,False,False,False,True,False,False,True,False,False,False
19363,101.99,58857.88,0,0,12,393.65,2,136,4607.34,0.6774,...,False,False,False,False,False,True,False,True,False,False
30157,1.18,45389.85,0,0,12,471.46,2,159,819.75,0.9482,...,False,True,True,False,False,False,False,False,False,True
14294,11.20,58021.75,0,1,1,86.75,4,61,4477.19,0.9004,...,False,False,False,False,False,True,False,False,True,False

In [215]:
y_train

8950     0
38421    0
19363    0
30157    1
14294    1
        ..
43723    0
32511    0
5192     1
12172    1
33003    0
Name: Fraud_Label, Length: 35000, dtype: int64

### Logistic Regression

In [216]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_res, y_train_res)
y_pred = lr.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[8931, 1210],
       [1731, 3128]], dtype=int64)

### Random Forest

In [217]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=2)
rf.fit(X_train_res, y_train_res)
y_pred = rf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[10141,     0],
       [    0,  4859]], dtype=int64)